alumni/urls.py
"""alumni URL Configuration"""

from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('NotAnAdmin/', admin.site.urls),
    path('', include('appcore.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appcore/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('form/', views.registerform, name="form"),
    path('a/', views.BookListView.as_view(), name="formss"),
    path('login/', views.login_page, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('staff-signin/', views.staff_signin_page, name="staff_signin"),
    path('signin/', views.signin_page, name="signin"),
    path('success/', views.registraion_success, name="registraion_success"),
    path('account-success/', views.account_success, name="account_success"),
    path('records/', views.records, name="records"),
    path('humans.txt/', views.humanstxt, name="humanstxt"),
    path('dashboard/approved/', views.dashboard_approved, name="dashboard_approved"),
    path('dashboard/all/', views.dashboard_all, name="dashboard_all"),
    path('dashboard/rejected/', views.dashboard_rejected, name="dashboard_rejected"),
    path('dashboard/pending/', views.dashboard_pending, name="dashboard_pending"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('documentation/', views.documentation, name="documentation"),
    path('view/<str:pk>/', views.view_alumni, name="view_alumni"),
    path('update/<str:pk>/', views.update_alumni, name="update_alumni"),
    path('delete/<str:pk>/', views.delete_alumni, name="delete_alumni"),
    path('account/', views.accountview, name="accountView"),
    path('student/', views.studentview, name="studentView"),
    path('account/update/', views.accountUpdate, name="accountUpdate"),
]

appcore/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class StaffAccount(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    profile_pic = models.ImageField(default="profile.png", null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name
#

class Alumni(models.Model):
    BRANCH = (
                ('CS', 'CS&E'),
                ('CV', 'CIVIL'),
                ('EC', 'E&C'),
                ('ME', 'MECH'),
                )
    GENDER = (
                ('Male', 'Male'),
                ('Female', 'Female'),
                ('Others', 'others'),
                )

    YEAR = (
                ('2012', '2012'),
                ('2013', '2013'),
                ('2014', '2014'),
                ('2015', '2015'),
                ('2016', '2016'),
                ('2017', '2017'),
                ('2018', '2018'),
                ('2019', '2019'),
                ('2020', '2020'),
                ('2021', '2021'),
                ('2022', '2022'),
                )
    STATUS = (
                ('Pending', 'Pending'),
                ('Accepted', 'Accepted'),
                ('Rejected', 'Rejected'),
                )
    usn = models.CharField(primary_key = True, max_length=10)
    firstname = models.CharField(max_length=200, null=True)
    lastname = models.CharField(max_length=200, null=True)
    staff = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=20, null=True)
    email = models.CharField(max_length=200, null=True)
    birthdate = models.DateField(null=True)
    profile_pic = models.ImageField(default="profile.png", null=True, blank=True)
    branch = models.CharField(max_length=20, null=True, choices=BRANCH)
    gender = models.CharField(max_length=20, null=True, choices=GENDER)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status =  models.CharField(default="Pending", max_length=20, null=True, choices=STATUS)
    pass_year =  models.CharField(max_length=4, null=True, choices=YEAR)

    def __str__(self):
        return self.usn

    def get_authors(self):
        return ', '.join(self.employers.all().values_list('Employer_name', flat=True))


class Employer(models.Model):
    alumni = models.ForeignKey(
            Alumni,
            related_name='employers', on_delete=models.SET_NULL, null=True)
    Employer_name = models.CharField(max_length=100, null=True)
    Employer_Designation = models.CharField(max_length=100, null=True)
    Employer_join_year = models.CharField(max_length=4, null=True)


    def __str__(self):
        return self.Employer_name

appcore/forms.py
from django.forms import ModelForm, formset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import *

class  AlumniForm(ModelForm):
    class Meta:
        model = Alumni
        fields = '__all__'
        exclude = ['staff','status']
        widgets = {
           'birthdate': forms.DateInput(format=('%d %B, %Y'), attrs={'type':"date"}),
        }


class  EmployerForm(ModelForm):
    class Meta:
        model = Employer
        fields = '__all__'
        exclude = ['alumni']


class  AlumniUpdateForm(ModelForm):
    class Meta:
        model = Alumni
        fields = '__all__'
        widgets = {
           'birthdate': forms.DateInput(format=('%d %B, %Y'), attrs={'type':"date"}),
           'staff': forms.TextInput(attrs={'type': 'hidden'}),
           'usn': forms.TextInput(attrs={'type': 'hidden'})
        }

class CreateStaffForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name', 'email', 'password1', 'password2']

class StaffAccountForm(ModelForm):
    class Meta:
        model = StaffAccount
        fields = '__all__'
        exclude = ['user']


EmployerFormset = formset_factory(EmployerForm ,extra=1)

appcore/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.views import generic


from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .forms import AlumniForm, StaffAccountForm, CreateStaffForm, AlumniUpdateForm, EmployerFormset

from django.core.paginator import Paginator
from django.shortcuts import render

from .models import Alumni, StaffAccount,Employer
from .decorators import unauthenticated_user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group


# views starts here

def home(request):
	return render(request, 'appcore/home.html', {'title':"Home - Alumni"})


def humanstxt(request):
	return render(request, 'appcore/humans.txt')


def registraion_success(request):
	return render(request, 'appcore/success_registration.html', {'title':"Success - Alumni"})


def account_success(request):
	return render(request, 'appcore/success_account.html', {'title':"Success - Alumni"})


class BookListView(generic.ListView):
    model = Alumni
    context_object_name = 'Alumnis'
    print(context_object_name)
    template_name = 'appcore/a.html'


def registerform(request):
    if request.method == 'POST':
        alumniForm = AlumniForm(request.POST, request.FILES)
        employerFormset = EmployerFormset(request.POST)
        if alumniForm.is_valid() and employerFormset.is_valid():
            alumni = alumniForm.save()
            for form in employerFormset:
                employer = form.save(commit=False)
                employer.alumni = alumni
                employer.save()
                return redirect('/success')
    alumniForm = AlumniForm()
    employerFormset = EmployerFormset()
    context = {'Alumniform': alumniForm,'EmployerFormset': employerFormset,'title':"Alumni Registration - Alumni"}
    return render(request, 'appcore/form_registration1.html', context)


# need authentication pages
@login_required(login_url='login')
def documentation(request):
    return render(request, 'appcore/documentation.html', {'title':"Documentation - Alumni"})


def logoutUser(request):
	logout(request)
	return redirect('login')


@unauthenticated_user
def signin_page(request):
    form =  CreateStaffForm()
    if request.method == 'POST':
        form = CreateStaffForm(request.POST)
        if form.is_valid():
            user = form.save()
            # user.is_active = False
            user.save()
            group = Group.objects.get(name='staff')
            user.groups.add(group)
            StaffAccount.objects.create(
                user=user,
                name=user.username,
                 )
            return redirect('account_success')
    context = {'form' : form,'title':"Sign in - Alumni"}
    return render(request, 'appcore/form_signin.html', context)
    
@unauthenticated_user
def staff_signin_page(request):
    form =  CreateStaffForm()
    if request.method == 'POST':
        form = CreateStaffForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.is_active = False
            user.save()
            group = Group.objects.get(name='staff')
            user.groups.add(group)
            StaffAccount.objects.create(
                user=user,
                name=user.username,
                 )
            return redirect('account_success')
    context = {'form' : form,'title':"Sign in - Alumni"}
    return render(request, 'appcore/form_signin.html', context)


@unauthenticated_user
def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
           login(request, user)
           return redirect('dashboard')
        else:
            messages.info(request, 'Username OR password is incorrect (or) contact Admin if both are correct')

    context = {'title':"Login - Alumni"}
    return render(request, 'appcore/form_login.html', context)


@login_required(login_url='login')
def dashboard(request):
    alumni = Alumni.objects.all()
    total_alumni = alumni.count()
    approved_alumni = alumni.filter(status='Accepted').count()
    rejected_alumni = alumni.filter(status='Rejected').count()
    pending_alumni = alumni.filter(status='Pending').count()

    branches = ['CS', 'CV', 'EC', 'ME']
    years = [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,2023]
    # years = alumni.values_list('pass_year', flat=True).distinct().order_by('pass_year')
    tablevaluess = []

    for year in years:
        locallist = []
        yearBool = True
        for branch in branches:
            if yearBool :
                locallist.append(year)
                yearBool = False
            localitem = alumni.filter(pass_year=year, branch=branch).count()
            locallist.append(localitem)
        tablevaluess.append(locallist)


    userName = request.user
    staffAccount = StaffAccount.objects.get(user=request.user.id)
    print(staffAccount.name)

    context = {'total_alumni':total_alumni, 'approved_alumni':approved_alumni,
    'rejected_alumni':rejected_alumni,'pending_alumni':pending_alumni,'title':"Dashboard - Alumni", 'userName':userName, 'tablevaluess' : tablevaluess}
    return render(request, 'appcore/dashboard_stats.html', context)


@login_required(login_url='login')
def dashboard_all(request):
    filter_dict = {}
    userName = request.user;
    alumni = []

    if request.method == 'POST':
        if 'filterSubmit' in request.POST:
            filter_list = ('pass_year', 'branch', 'gender', 'status')
            for filter in filter_list:
                val = request.POST.get(filter)
                if not (val == '') :
                    filter_dict[filter] = val

        if 'searchNormalWithCategory' in request.POST:
            search_catogery = request.POST.get('search_catogery')
            search_word = request.POST.get('search_word')
            filter_dict[search_catogery] = search_word

        alumni = Alumni.objects.filter(**filter_dict ).order_by('usn')

    else:
        alumni = Alumni.objects.all().order_by('usn')

    paginator = Paginator(alumni, 60) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    userName = request.user;
    context = {'page_obj': page_obj,'title':"All registered - Alumni", 'highlight_menu':'dash_bar_list_all_registered', 'userName':userName,  'filter_dict': filter_dict}
    return render(request, 'appcore/dashboard_approved.html',context )


@login_required(login_url='login')
def dashboard_approved(request):
    alumni = Alumni.objects.filter(status="Accepted").order_by('usn')
    paginator = Paginator(alumni, 60) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    userName = request.user;
    context = {'page_obj': page_obj,'title':"dashboard - Alumni", 'highlight_menu':'dash_bar_list_approved', 'userName':userName}
    return render(request, 'appcore/dashboard_approved.html',context )


@login_required(login_url='login')
def dashboard_pending(request):
    alumni = Alumni.objects.filter(status="Pending").order_by('usn')
    paginator = Paginator(alumni, 60) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    userName = request.user;
    return render(request, 'appcore/dashboard_approved.html',{'page_obj': page_obj,'title':"dashboard - Alumni", 'highlight_menu':'dash_bar_list_pending', 'userName':userName})


@login_required(login_url='login')
def dashboard_rejected(request):
    alumni = Alumni.objects.filter(status="Rejected").order_by('usn')
    paginator = Paginator(alumni, 60,orphans=10) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    userName = request.user
    return render(request, 'appcore/dashboard_approved.html',{'page_obj': page_obj,'title':"dashboard - Alumni", 'highlight_menu':'dash_bar_list_rejected', 'userName' : userName})


@login_required(login_url='login')
def update_alumni(request, pk):
    alumni =  Alumni.objects.get(usn=pk)
    userName = request.user;
    form = AlumniUpdateForm(initial={'staff': userName}, instance=alumni)

    if request.method == 'POST':
        form = AlumniUpdateForm(request.POST,request.FILES, instance=alumni)
        if form.is_valid():
           form.save()
           message_text = alumni.firstname + alumni.lastname + '('+ alumni.usn + ')' + ' is updated'
           messages.info(request, message_text)
           return redirect(reverse('view_alumni',args=[alumni.usn]))
    context = {'form': form,'alumni':alumni.usn,'title':"Update Alumni - Alumni", 'userName': userName }
    return render(request, 'appcore/alumni_update.html',context )


@login_required(login_url='login')
def view_alumni(request, pk):
    alumni =  Alumni.objects.get(usn=pk)
    print(alumni)
    employers = Employer.objects.filter(alumni_id=alumni.usn).order_by("Employer_join_year")
    print(employers)
    for employ in employers:
        print("---------------------------------")
        print(employ.Employer_name)
        print(employ.Employer_Designation)
        print(employ.Employer_join_year)
        print(employ.alumni_id)
        print("---------------------------------")
    return render(request, 'appcore/alumni_view.html', {'alumni':alumni,"employers":employers ,'title':"View Alumni - Alumni"})


@login_required(login_url='login')

appcore/templates/appcore/a.html
{% extends 'appcore/dashbar.html' %}

{% load static %}

{% block content %}

<table class="table">
    <tr>
        <th>Book</th>
        <th>Author</th>
    </tr>
{% for book in Alumnis %}
    <tr>
    {{book}}
        <td>{{book.usn}}</td>
        <td>{{book.get_authors}}</td>
    </tr>
{% endfor %}
</table>

{% endblock %}

appcore/templates/appcore/account_update.html
{% extends 'appcore/dashbar.html' %}

{% load static %}

{% block content %}

<div class="right-panel pad_left_right">
    <div class="right_panel_card_edit_alum">
<div class="editpage_header">
Profile Update
</div>
  <div class="editpage_head">
  </div>

        <form class="remove_form_style" method="post" enctype="multipart/form-data">
            {% csrf_token %}
        <div class="margin-down">
          <div class="margin-down">
            <label for="id_name">Name</label>
            {{form.name}}
          </div>
          <div class="margin-down">
            <label for="id_name">Phone</label>
            {{form.phone}}
          </div>
          <div class="margin-down">
            <label for="id_name">Email</label>
            {{form.email}}
          </div>
          <div class="margin-down">
            <label for="id_name">Profile Photo</label>
            {{form.profile_pic}}
          </div>
        </div>
           <div class="left-float">
                <a href="{% url 'accountView' %}" class="button " >Cancel</a>
               <input type="submit" class="button margin_right" name="submit" value="Update">
           </div>
        </form>
     </div>
</div>
<script type="text/javascript">
    const highlight_menu = document.getElementById('dash_bar_list_profile')
    if (highlight_menu) {
        highlight_menu.classList.add("lm-list-item-active")
    }
</script>
{% endblock %}

appcore/templates/appcore/form_registration.html
{% extends 'appcore/headAndFoot.html' %}

{% load static %}

{% block content %}
	<form class="" method="post" enctype="multipart/form-data" >
	{% csrf_token %}
      <div class="formheading heading">Alumni Registration</div>
      <div class="margin-down danger_color">
          {% if form.errors %}
          {% for field in form %}

               {% for error in field.errors %}
                    {{field.label}}: {{ error|escape }}
               {% endfor %}

          {% endfor %}
    {% endif %}
      </div>

	  <div class="margin-down">
	  	<label for="id_profile_pic">
	  		<span id="labelImage"></span>
	  	</label>
	  </div>
	  <div class="margin-down">
		  <label for="id_usn">University Registration Number</label>
          {{ form.usn }}
	  </div>
   <div class="divide two margin-down">
     <div class="df">
       <label for="id_firstname">First Name</label>
       {{ form.firstname }}
     </div>
     <div>
       <label for="id_lastname">Last Name</label>
       {{ form.lastname }}
     </div>
   </div>
   <div class="divide two margin-down">
     <div class="df">
       <label for="id_phone">Phone</label>
       {{ form.phone }}
     </div>
     <div>
       <label for="id_email">Email</label>
        {{ form.email }}
     </div>
   </div>
   <div class="margin-down">
   	<label for="id_profile_pic">Photo upload</label>
	{{ form.profile_pic}}
   </div>
   <div class="divide three margin-down">
     <div class="df">
       <label for="id_gender">gender</label>
        {{ form.gender }}
     </div>
     <div>
       <label for="id_birthdate">Date of birth</label>
        {{ form.birthdate }}
     </div>
     <div class="df">
     <label class="rp-options-item" for="id_pass_year">Passing year</label>
	{{ form.pass_year }}
     </div>
     <div class="df">
       <label for="id_branch">Branch</label>
		{{ form.branch }}
     </div>
   </div>
      </div>
        <div class="flexbox-one margin-down">
             <input id="t-and-c-agree" required class="checkbox" type="checkbox" tabindex="0">
             <label class="check-label" for="t-and-c-agree" >I agree to the Terms and Conditions</label>
           </div>
      <div class="left-float">
		  <input type="submit" name="submit" class="button" value="Submit">
      </div>

    </form>

<script type="text/javascript">

	document.getElementById("id_usn").placeholder = "USN"
	document.getElementById("id_firstname").placeholder = "First Name"
	document.getElementById("id_lastname").placeholder = "Last Name"
	document.getElementById("id_phone").placeholder = "Phone Number"
	document.getElementById("id_email").placeholder = "Email"
	document.getElementById("id_birthdate").placeholder = "Date of Birth"
	document.getElementById("id_present_Employer").placeholder = "Present Employer"
	document.getElementById("id_present_Designation").placeholder = "Designation"
	document.getElementById("id_present_Employer_join_year").placeholder = "Join Year ex. 2021"
	document.getElementById("id_previous_Employer").placeholder = "Previous Employer"
	document.getElementById("id_previous_Designation").placeholder = "Designation"
	document.getElementById("id_previous_Employer_join_year").placeholder = "Join Year ex. 2021"

	const propicinput = document.getElementById("id_profile_pic")
	const labelImage = document.getElementById("labelImage")

	id_profile_pic.addEventListener("change", handlefor)

	function handlefor(e) {
	      const img = document.createElement("img");
	      console.log(this.files);
	      img.src = URL.createObjectURL(this.files[0]);
	      img.className = 'imagestyle';
	      img.onload = function() {
	        URL.revokeObjectURL(this.src);
	      }
	      labelImage.appendChild(img);
	}

</script>


	{% endblock %}

appcore/templates/appcore/form_registration1.html
{% extends 'appcore/headAndFoot.html' %}

{% load static %}

{% block content %}
<style media="screen">
    .just-between{
            justify-content: space-between;
    }

    .delete_employment_row{
        display:inline-block;
    }
    .delete_employment_row:hover{
                background:red;
    }
    .rightflex{
display:flex;
flex-direction:row-reverse;
    }
</style>

	<form class="" method="post" enctype="multipart/form-data" >
	{% csrf_token %}
      <div class="formheading heading">Alumni Registration</div>
      <div class="margin-down danger_color">
          {% if form.errors %}
          {% for field in form %}

               {% for error in field.errors %}
                    {{field.label}}: {{ error|escape }}
               {% endfor %}

          {% endfor %}
    {% endif %}
      </div>

	  <div class="margin-down">
	  	<label for="id_profile_pic">
	  		<span id="labelImage"></span>
	  	</label>
	  </div>
 <div class="margin-down">
		  <label for="id_usn">University Registration Number</label>
          {{ Alumniform.usn }}
	  </div>
   <div class="divide two margin-down">
     <div class="df">
       <label for="id_firstname">First Name</label>
       {{ Alumniform.firstname }}
     </div>
     <div>
       <label for="id_lastname">Last Name</label>
       {{ Alumniform.lastname }}
     </div>
   </div>
   <div class="divide two margin-down">
     <div class="df">
       <label for="id_phone">Phone</label>
       {{ Alumniform.phone }}
     </div>
     <div>
       <label for="id_email">Email</label>
        {{ Alumniform.email }}
     </div>
   </div>
   <div class="margin-down">
   	<label for="id_profile_pic">Photo upload</label>
	{{ Alumniform.profile_pic}}
   </div>
   <div class="divide three margin-down">
     <div class="df">
       <label for="id_gender">gender</label>
        {{ Alumniform.gender }}
     </div>
     <div>
       <label for="id_birthdate">Date of birth</label>
        {{ Alumniform.birthdate }}
     </div>
     <div class="df">
     <label class="rp-options-item" for="id_pass_year">Passing year</label>
	{{ Alumniform.pass_year }}
     </div>
     <div class="df">
       <label for="id_branch">Branch</label>
		{{ Alumniform.branch }}
     </div>
   </div>
     <input type="hidden" name="form-TOTAL_FORMS" value="1" id="id_form-TOTAL_FORMS">
     <input type="hidden" name="form-INITIAL_FORMS" value="0" id="id_form-INITIAL_FORMS">
     <input type="hidden" name="form-MIN_NUM_FORMS" value="0" id="id_form-MIN_NUM_FORMS">
     <input type="hidden" name="form-MAX_NUM_FORMS" value="1000" id="id_form-MAX_NUM_FORMS">
     
     <div class="margin-down">
     <label for="id_form-0-Employer_name">Present Employer name:</label>   
    <input type="text" name="form-0-Employer_name" maxlength="100" id="id_form-0-Employer_name">
</div>
  <div class="divide two margin-down">
  <div  class="margin-down"> 
      <label for="id_form-0-Employer_Designation">Present Designation:</label>
   <input type="text" name="form-0-Employer_Designation" maxlength="100" id="id_form-0-Employer_Designation">
</div>
     <div class="margin-down">
  <label for="id_form-0-Employer_join_year">join year:</label>
<input type="text" name="form-0-Employer_join_year" maxlength="4" id="id_form-0-Employer_join_year">   
</div>
</div>
    <div id="spaceforAppend"></div>
    <div class="margin-down">
     <a href="#" id="addNewFieldBtn" class="button">+ Add Another Employement</a>
   </div>
   <div class="flexbox-one margin-down">
             <input id="t-and-c-agree" required class="checkbox" type="checkbox" tabindex="0">
             <label class="check-label" for="t-and-c-agree" >I agree to the Terms and Conditions</label>
           </div>
   <div class="rightflex">
 <input type="submit" name="submit" class="button" value="Submit">
   </div>

<script type="text/javascript">


	document.getElementById("id_usn").placeholder = "USN"
	document.getElementById("id_firstname").placeholder = "First Name"
	document.getElementById("id_lastname").placeholder = "Last Name"
	document.getElementById("id_phone").placeholder = "Phone Number"
	document.getElementById("id_email").placeholder = "Email"
	document.getElementById("id_birthdate").placeholder = "Date of Birth"
	document.getElementById("id_form-0-Employer_name").placeholder = "Present Employer"
	document.getElementById("id_form-0-Employer_Designation").placeholder = "Designation"
	document.getElementById("id_form-0-Employer_join_year").placeholder = "Join Year ex. 2021"

	const propicinput = document.getElementById("id_profile_pic")
	const labelImage = document.getElementById("labelImage")

	id_profile_pic.addEventListener("change", handlefor)

	function handlefor(e) {
	      const img = document.createElement("img");
	      console.log(this.files);
	      img.src = URL.createObjectURL(this.files[0]);
	      img.className = 'imagestyle';
	      img.onload = function() {
	        URL.revokeObjectURL(this.src);
	      }
	      labelImage.appendChild(img);
	}



    const countElement = document.getElementById('id_form-TOTAL_FORMS')
    const intialCountElement = document.getElementById('id_form-INITIAL_FORMS')
    const max = 1000;

    const addNewFieldBtn  = document.getElementById("addNewFieldBtn");
    const spaceforAppend  = document.getElementById("spaceforAppend");

    addNewFieldBtn.addEventListener("click",addNewField)
    spaceforAppend.addEventListener("click",removeField)

    function addNewField(e) {
      e.preventDefault();
     const newfieldcount =  Number(intialCountElement.value) + Number(countElement.value) + 1;
      if (countElement.value < 100) {
      const EmployementTemplate = `
      <div class="margin-down">
          <div class="flexbox-one just-between red ">
               <label for="id_form-${newfieldcount}-Employer_name">Previous Company Name #${newfieldcount} :</label>
              <span> <a  class="delete_employment_row" href="#" title="delete this row" class="red">  <img class="delete_row_icon" src="{% static 'images/delete_forever_black_24dp.svg' %}" alt=""> </a> </span>
          </div>
          <input type="text" name="form-${newfieldcount}-Employer_name" maxlength="100" id="id_form-${newfieldcount}-Employer_name">
      </div>
      <div class="divide two margin-down">
          <div class="df">
              <label for="id_form-${newfieldcount}-Employer_Designation">Designation :</label>
              <input type="text" name="form-${newfieldcount}-Employer_Designation" maxlength="100" id="id_form-${newfieldcount}-Employer_Designation">
          </div>
          <div>
              <label for="id_form-${newfieldcount}-Employer_join_year">Joining Year</label>
              <input type="text" name="form-${newfieldcount}-Employer_join_year" maxlength="4" id="id_form-${newfieldcount}-Employer_join_year">
          </div>
      </div>`;

    const div = document.createElement('div');
    div.classList = "extra_employement_row";
    div.innerHTML = EmployementTemplate;
    spaceforAppend.append(div)
    countElement.value = newfieldcount;
    }
    }

function removeField(e) {
e.preventDefault();
// const newfieldcount =  Number(intialCountElement.value) + Number(countElement.value) + 1;
 if (countElement.value >= 1) {
     if (e.target.tagName =="IMG" && e.target.className == "delete_row_icon") {
         if (e.target.parentElement.parentElement.parentElement.parentElement.parentElement.classList.contains("extra_employement_row")) {
            e.target.parentElement.parentElement.parentElement.parentElement.parentElement.remove()
            countElement.value = countElement.value - 1
         }
     }
     if (e.target.tagName =="a" && e.target.className == "delete_employment_row") {
         if (e.target.parentElement.parentElement.parentElement.parentElement.classList.contains("extra_employement_row")) {
            e.target.parentElement.parentElement.parentElement.parentElement.remove()
            countElement.value = countElement.value - 1

         }
     }

 }

 const start = 2;

 document.querySelectorAll('.extra_employement_row').forEach((item, i) => {
    let count = start + i + 1;
     item.querySelectorAll('label').forEach((item1, i) => {
         const arr = item1.getAttribute('for').split("-")
         const newline = arr[0] + '-' + count + '-' + arr[2]
         if (item1.getAttribute('for').indexOf("Employer_name") != -1) {
            item1.textContent  = "Previous Company Name #" + count + " :"
         }
        item1.setAttribute("for",newline)
     });
     item.querySelectorAll('input').forEach((item1, i) => {
        const arr = item1.getAttribute('name').split("-")
        const newline = arr[0] + '-' + count + '-' + arr[2];
        item1.id = newline;
        item1.setAttribute("name",newline)
     });

 });

}

</script>
	{% endblock %}